### ISSUE TITLE
Consider moving to MailHog instead of Mailcatcher

### ISSUE THREAD

**Issue by joesb** [wunderkraut/Ansibleref#1]
[Mailcatcher](http://mailcatcher.me/) has always proved a pig to install and the source of many problems in keeping Ansibleref maintained.

We might consider moving to a Mailcatcher alternative, and [MailHog](https://github.com/mailhog/MailHog) looks like a good one. MailHog's strapline: 

> Inspired by MailCatcher, easier to install.

There's even a ready-to-go [MailHog Ansible role](https://github.com/geerlingguy/ansible-role-mailhog/) available - woop!

**Comment by aleksijohansson** [comment]
+1, MailCatcher is a pain

**Comment by tharna** [comment]
Mailcathcer replaced with Mailhog

**Comment by joesb** [comment]
Woo hoo! Great news!
